DROP TABLE IF EXISTS posts;
CREATE TABLE IF NOT EXISTS posts (id SERIAL PRIMARY KEY, title VARCHAR(255), content VARCHAR(255));

DROP TABLE IF EXISTS tweets;
CREATE TABLE IF NOT EXISTS tweets (id SERIAL PRIMARY KEY, title VARCHAR(255), content VARCHAR(255));